import React, { useState, useEffect } from 'react';
import { Download, FileText, RefreshCw, CheckCircle, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useLanguage } from '@/contexts/LanguageContext';
import { useFormContext } from '@/contexts/FormContext';

export function DownloadPage() {
  const { t } = useLanguage();
  const { selectedForm, extractedFields, resetForm, setCurrentStep } = useFormContext();
  const [isGenerating, setIsGenerating] = useState(true);
  const [pdfReady, setPdfReady] = useState(false);

  useEffect(() => {
    // Simulate PDF generation
    const timer = setTimeout(() => {
      setIsGenerating(false);
      setPdfReady(true);
    }, 2000);

    return () => clearTimeout(timer);
  }, []);

  const handleDownload = () => {
    // In production, this would generate an actual PDF
    // For now, we'll create a simple text file as demonstration
    const formData = extractedFields
      .map(f => `${f.key}: ${f.value}`)
      .join('\n');

    const content = `
${selectedForm?.name || 'Government Form'}
Generated by Seva Sahayak
Date: ${new Date().toLocaleDateString('en-IN')}

--- Form Data ---
${formData}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedForm?.id || 'form'}_filled.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleStartNew = () => {
    resetForm();
    setCurrentStep(0);
  };

  if (isGenerating) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <div className="relative mb-8">
          <div className="w-32 h-32 rounded-full bg-primary/10 flex items-center justify-center">
            <FileText className="w-16 h-16 text-primary animate-pulse" />
          </div>
          <div className="absolute -bottom-2 -right-2 w-12 h-12 rounded-full bg-primary flex items-center justify-center">
            <RefreshCw className="w-6 h-6 text-primary-foreground animate-spin" />
          </div>
        </div>
        
        <h2 className="text-2xl font-bold mb-2">Generating Your Form...</h2>
        <p className="text-muted-foreground">Please wait while we prepare your PDF</p>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto space-y-8">
      {/* Success State */}
      <div className="text-center">
        <div className="inline-flex items-center justify-center w-24 h-24 rounded-full bg-accent/10 mb-6">
          <CheckCircle className="w-12 h-12 text-accent" />
        </div>
        <h2 className="text-3xl font-bold mb-2">{t('download.title')}</h2>
        <p className="text-muted-foreground text-lg">{t('download.subtitle')}</p>
      </div>

      {/* Form Summary Card */}
      <Card className="bg-gradient-to-br from-card to-muted/50">
        <CardContent className="p-6">
          <div className="flex items-start gap-4">
            <div className="w-16 h-16 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
              <FileText className="w-8 h-8 text-primary" />
            </div>
            <div className="flex-1">
              <h3 className="text-xl font-semibold mb-1">{selectedForm?.name}</h3>
              <p className="text-muted-foreground mb-4">
                Filled with {extractedFields.filter(f => f.value).length} fields
              </p>
              
              {/* Quick preview of filled data */}
              <div className="grid grid-cols-2 gap-2 text-sm">
                {extractedFields.slice(0, 4).map(f => (
                  <div key={f.key} className="truncate">
                    <span className="text-muted-foreground">{f.key}: </span>
                    <span className="font-medium">{f.value || '-'}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Download Actions */}
      <div className="flex flex-col sm:flex-row gap-4">
        <Button 
          variant="hero" 
          size="xl" 
          className="flex-1"
          onClick={handleDownload}
          disabled={!pdfReady}
        >
          <Download className="w-6 h-6 mr-2" />
          {t('download.button')}
        </Button>
        <Button 
          variant="outline" 
          size="xl"
          className="flex-1"
          onClick={() => window.print()}
        >
          <Printer className="w-6 h-6 mr-2" />
          Print
        </Button>
      </div>

      {/* Security Notice */}
      <Card className="bg-accent/5 border-accent/20">
        <CardContent className="p-4 text-center">
          <p className="text-sm text-muted-foreground">
            ✓ Your documents have been automatically deleted from our servers.
            <br />
            No personal data is stored.
          </p>
        </CardContent>
      </Card>

      {/* Start New Button */}
      <div className="text-center pt-4">
        <Button variant="ghost" size="lg" onClick={handleStartNew}>
          <RefreshCw className="w-5 h-5 mr-2" />
          {t('download.startNew')}
        </Button>
      </div>
    </div>
  );
}
